title: "rass0x4f"
author: "rass0x4f"
description: "Made with <b style=\"color: #f45;\">&lt;3</b>"
permalink: /:year/:month/:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "blog.md", title: "Blog", icon: clipboard}
  

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:fattaharrasyid90@gmail.com"}
  - {title: Github, icon: github, url: "https://github.com/Rass0x4f"}
  - {title: Twitter, icon: "twitter", url: "https://twitter.com/rass0x4f"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
